### ISSUE TITLE
Some minor ideas

### ISSUE THREAD

**Issue by m-artin** [jenstornell/splitview#105]
As I already mentioned in the forum: Splitview is really, really great! 
All thumbs up. Hope it is o.k. to share my experience and small suggestions here. 
I am on a Mac btw.

• Is it possible to save the user-settings of the Splitview-layout in 'Local Browser Storage' or something like that?
This way, even after a refresh splitview could start up with the custom settings. 
(Currently I have to set up my preferred layout often, when a complete browser refresh is needed. For example after logging into the panel again, when Kirbs asks for a re-login after a certain amount of time.)

• Keyboard-Shortcuts for:
 - Expand view 1 or 2 to 100% (in order to quickly hide panel / site view, even in distraction-free mode)
 - Toggle Distraction-Free mode with keyboard shortcut

• Is it possible to show a button inside the Kirby panel to activate splitview (independent of panel bar)?

**Comment by jenstornell** [comment]
### Local storage

Some values should be saved to local storage but I've built more and more features and all of them needs to be added to the local storage as well. I have some issues for it so when I start working on this thing again they will probably be there.

### Keyboard shortcuts

There is a reason why there are no keyboard shortcut when in Splitview. Often an iframe has the focus because you click arount in iframes. When in an iframe it's the iframe shortcut that will fire, not the parent. Splitview are no longer in control of the shortcuts and I can't control the panel or the site. Even if I could, I could not make a shortcut work from inside an iframe up to the parent.

I could make it lose focus every 100ms or so but then it would not be fun to write in textareas for example.

### Yes. I have an issue for that too. The reason I wait is that there is no good way to add anything to the panel yet, except for fields but fields only work on panel pages. I know that they are working on panel customizations and I hope that means adding stuff to the menus. In that case I will add it to a menu in the panel, or a sidebar if possible.

**Comment by m-artin** [comment]
Thanks for your instant feedback. 
Sounds great. 

Regarding the keyboard shortcuts:
I have built a small workaround for the Auto-Sync issue on mac. 
So perhaps this might be possible with parent.document or window.top

```
			// sync after shortcut (CTRL + a)
			document.onkeyup=function(e){
					var e = e || window.event; // for IE to cover IEs window object
				if(e.ctrlKey && e.which == 65) {
					// alert('Keyboard shortcut working!');
					parent.document.querySelector("#split2 .sync").click();
					 return false;
				}
			}
```

**Comment by jenstornell** [comment]
Great! Will look into it when I got the time.
